export const ALGORITHM_BRUTAL_FORCE = { key: 'BRUTAL_FORCE', label: 'Brutal' };
export const ALGORITHM_GRID_TRADING = { key: 'GRID_TRADING', label: 'Grid' };
export const ALGORITHM_GRID_TRADING_RESPECT_LOWER = {
  key: 'GRID_TRADING_RESPECT_LOWER',
  label: 'Grid Respect Lower',
};
export const ALGORITHM_GRID_TRADING_OBSERVE_PROFIT = {
  key: 'GRID_TRADING_OBSERVE_PROFIT',
  label: 'Grid Observe Profit',
};

export const ALGORITHM_TYPES = [
  ALGORITHM_BRUTAL_FORCE,
  ALGORITHM_GRID_TRADING,
  ALGORITHM_GRID_TRADING_RESPECT_LOWER,
  ALGORITHM_GRID_TRADING_OBSERVE_PROFIT,
];
