export const CHANNEL_COINBASE_CRYPTO = { key: 'COINBASE_CRYPTO', label: 'Coinbase' };
export const CHANNEL_INTERACTIVE_BROKERS_STOCK = { key: 'INTERACTIVE_BROKERS_STOCK', label: 'IB' };
export const CHANNEL_FOREX_STANDARD_ACCOUNT = { key: 'FOREX_STANDARD_ACCOUNT', label: 'Forex' };

export const CHANNEL_TYPES = [
  CHANNEL_COINBASE_CRYPTO,
  CHANNEL_INTERACTIVE_BROKERS_STOCK,
  CHANNEL_FOREX_STANDARD_ACCOUNT,
];
