name: Deploy Prod Tencent bitcode-lab.com
run-name: PickTB Management ${{ github.actor }} trigger by ${{github.event_name}}
on: [workflow_dispatch]
jobs:
  build-deploy-application:
    env:
      BUILD_FOLDER: build/*
      ENV: prod
      SERVER_TARGET_FOLDER: /var/www/html/hive
      SERVER_TEMP_FOLDER: ~/temp/hive
      TENCENT_CLOUD_SSH_HOST: bitcode-lab.com
      TENCENT_CLOUD_SSH_USERNAME: ubuntu
      TENCENT_CLOUD_SSH_PORT: 22

    runs-on: ubuntu-latest
    name: "Build and Deploy Application"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
      - run: npm install
      - run: npm run build-${{ env.ENV }}
        env:
          CI: false

      - name: "move build to Tencent temp"
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.TENCENT_CLOUD_SSH_HOST }}
          username: ${{ env.TENCENT_CLOUD_SSH_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_KEY }}
          port: ${{ secrets.TENCENT_CLOUD_SSH_PORT }}
          source: ${{ env.BUILD_FOLDER }}
          target: ${{ env.SERVER_TEMP_FOLDER }}

      - name: "Move Files From Temp Folder To Production Folder"
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.TENCENT_CLOUD_SSH_HOST }}
          username: ${{ env.TENCENT_CLOUD_SSH_USERNAME }}
          key: ${{ secrets.TENCENT_CLOUD_KEY }}
          port: ${{ env.TENCENT_CLOUD_SSH_PORT }}
          script: |
            cd ${{ env.SERVER_TARGET_FOLDER }}
            rm ./*
            rm -r avatars
            rm -r static
            mv ${{ env.SERVER_TEMP_FOLDER }}/${{ env.BUILD_FOLDER }} ${{ env.SERVER_TARGET_FOLDER }}
